DAY-J/BackEnd

pom.xml
src/main/resources/application.properties

@SpringBootApplication 어노테이션이 oauth, dayj 2개 클래스에 존재해서 pom.xml에 main 클래스 경로 설정해주었습니다. 
서버 빌드 시 에러가 떴었는데 경로 설정으로 해결했습니다.
* 서버 빌드 시 메인 클래스 못찾아 생기는 오류 해결 
* pom.xml 수정 
* 리디렉션 uri 환경 변수 추가 -> 서브 모듈 완료하고 서버 빌드 후 환경 변수 값 공지할 예정  
*
*
* P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 …

REFACTOR: pom.xml, 환경 변수 수정

---

.gitmodules

security repo를 submodule로 추가했습니다.
issue : X
* 
*
*
*
*
#
---

CHORE: submodule 추가

---

.gitmodules

submodule 수정 

---

.gitmodules

submodule 삭제

---

src/main/java/com/capstone/dayj/OauthSecurity/OAuth2SecurityConfiguration.java

서버 빌드 테스트하기 위해서 security -> OauthSecurity로 변경해서 올려볼게요 
issue: X
* 
*
*
*
*
#
---

FEAT: OauthSecurity 추가

---

src/main/java/com/capstone/dayj/friendGroup/FriendGroup.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupController.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupDto.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupRepository.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupService.java

friendGroup의 친구 그룹 나가기, 친구 그룹내의 목표 내용과 목표 달성여부를
체크할 수 있는 기능 추가. 또한 이메일 친구 불러오기 기능 추가
X
* 
* 친구 그룹 나가기 기능 추가
* 친구 그룹내의 목표 내용, 달성여부 체크 기능 추가
* 이메일로 친구 불러오기 기능 추가
* FriendGroup의 기능 추가
*
*
* P2 : 반영을 적극적으로 고려해 …

friendGroup 목표,달성여부,이메일 추가

---

src/main/java/com/capstone/dayj/friendGroup/FriendGroup.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupController.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupDto.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupRepository.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupService.java

Revert "friendGroup 목표,달성여부,이메일 추가"

---

src/main/java/com/capstone/dayj/appUser/AppUserService.java
src/main/java/com/capstone/dayj/plan/PlanService.java
src/main/java/com/capstone/dayj/planOption/PlanOption.java
src/main/java/com/capstone/dayj/planOption/PlanOptionController.java
src/main/java/com/capstone/dayj/planOption/PlanOptionRepository.java
src/main/java/com/capstone/dayj/planOption/PlanOptionService.java

* Plan이 만들어질 때, PlanOption도 생성되도록 수정
* Appuser로부터 Plan을 검색할 떄 AppUser 자체로 검색했는데 app_user_id로 검색하게 변경
* 테스트 부탁드려요
---

REFACTOR: Plan, PlanOption CREATE

---

src/main/java/com/capstone/dayj/appUser/AppUser.java
src/main/java/com/capstone/dayj/appUser/AppUserController.java
src/main/java/com/capstone/dayj/appUser/AppUserService.java
src/main/java/com/capstone/dayj/plan/Plan.java
src/main/java/com/capstone/dayj/plan/PlanController.java
src/main/java/com/capstone/dayj/plan/PlanRepository.java
src/main/java/com/capstone/dayj/plan/PlanService.java
src/main/java/com/capstone/dayj/planOption/PlanOption.java
src/main/resources/application-local.properties
src/main/resources/application-prod.properties
src/main/resources/application.properties

* CASCADING을 설정하지 않아 매핑이 된 ENTITY끼리 삭제할 수 없었습니다.
이를 Cascading.PERSIST, Cascading.REMOVE로 해결해주었습니다.
* 없음
* 일단 제가 담당한 ENTITY들만 Cascading 설정을 해주었습니다. 신형님이 담당하신 entity는 잘못 건들였다가 다 날라갈까봐 안해놨어요 Cascading 적용해주셔야합니다.
---

REFACTOR: AppUser, Plan CASCADING 수정

---

src/main/resources/application-local.properties
src/main/resources/application-prod.properties

* application.properties 변경으로 서버 다시 세팅하고 있습니다. 분리했을 시 작동하는지 테스트 해볼게요 
*
*
---

RED_URI prod와 local 분리 테스트

---

src/main/java/com/capstone/dayj/Oauth/OAuth2AppUserService.java
src/main/java/com/capstone/dayj/appUser/AppUser.java
src/main/java/com/capstone/dayj/appUser/AppUserController.java
src/main/java/com/capstone/dayj/appUser/AppUserService.java
src/main/java/com/capstone/dayj/plan/Plan.java
src/main/java/com/capstone/dayj/plan/PlanDto.java
src/main/java/com/capstone/dayj/planOption/PlanOption.java
src/main/java/com/capstone/dayj/setting/AlarmSetting.java
src/main/java/com/capstone/dayj/setting/Setting.java
src/main/java/com/capstone/dayj/setting/SettingController.java
src/main/java/com/capstone/dayj/setting/SettingDto.java
src/main/java/com/capstone/dayj/setting/SettingService.java

* Plan을 GET 할 때, PlanOption도 한 번에 받을 수 있도록 하려고 합니다.
* 이 때, 무한 재귀가 발생합니다. 따라서 이를 해결하기 위해 Plan과 PlanOption에 직렬화 어노테이션을 달아주었습니다.
* 없음
* 만약 GET 할 때, 매핑된 다른 엔티티도 한 번에 가져와야 하는 상황이라면 제가 Plan에 적용한 것처럼 해주어야 할 것 같습니다.
* 신형님이 맡으신 엔티티들도 적용해야하는지 확인 부탁드려요
---

REFACTOR: Plan 무한 재귀 해결

---

src/main/java/com/capstone/dayj/friendGroup/FriendGroup.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupDto.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupService.java
src/main/java/com/capstone/dayj/groupMember/GroupMemberService.java

FriendGroup에서 groupExit 필드를 삭제했습니다.
- 필드 삭제이기 때문에 ddl - update로 돌리거나 mySQL workbench에서 직접 드롭해야 오류가 발생하지 않습니다
- ALTER TABLE FriendGroup DROP COLUMN groupExit;
* service 클래스의 변수 명 수정 
* 수정해야 하는 것들 나중에 한번에 전달해주세요 ! 
---

REFACTOR: FriendGroup entity 수정, 변수명 수정

---

src/main/java/com/capstone/dayj/OauthSecurity/OAuth2SecurityConfiguration.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroup.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupController.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupDto.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupService.java
src/main/java/com/capstone/dayj/groupMember/GroupMember.java
src/main/java/com/capstone/dayj/groupMember/GroupMemberController.java
src/main/java/com/capstone/dayj/groupMember/GroupMemberDto.java
src/main/java/com/capstone/dayj/groupMember/GroupMemberService.java

- friendGroupId로 GET 할 시 그룹 회원 정보 (닉네임, isPulbic = True인 plan들)이 보여지도록 수정했습니다. 
- 겹치는 서비스는 삭제했습니다. (groupMember - readAllMemberInFriendGroup)
- Oauth2SecurityConfiguration 관련 -> SpringSecurity 버전에 맞춰서 .authorizeHttpRequests()로 변경했습니다. 
* 테스트 해주세요 ................ 
---

REFACTOR: FriendGroup 리팩토링

---

src/main/java/com/capstone/dayj/appUser/AppUserDto.java
src/main/java/com/capstone/dayj/comment/CommentDto.java
src/main/java/com/capstone/dayj/friendGroup/FriendGroupDto.java
src/main/java/com/capstone/dayj/planOption/PlanOption.java
src/main/java/com/capstone/dayj/planOption/PlanOptionDto.java
src/main/java/com/capstone/dayj/planOption/PlanOptionService.java

* DTO에서 JsonIgnore로 안쓰는 필드들 다 삭제
* 없으ㅜㅁ
* 아 순환참조 개빡친다진짜!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
---

REFACTOR: remove @JsonIgnore

---

.gitignore
pom.xml
src/main/java/com/capstone/dayj/DayJApplication.java
src/main/java/com/capstone/dayj/Oauth/OAuth2AppUserService.java
src/main/java/com/capstone/dayj/OauthSecurity/OAuth2SecurityConfiguration.java
src/main/java/com/capstone/dayj/appUser/AppUser.java
src/main/java/com/capstone/dayj/appUser/AppUserController.java
src/main/java/com/capstone/dayj/appUser/AppUserDto.java
src/main/java/com/capstone/dayj/appUser/AppUserService.java
src/main/java/com/capstone/dayj/comment/CommentController.java
src/main/java/com/capstone/dayj/comment/CommentService.java
src/main/java/com/capstone/dayj/exception/ErrorCode.java
src/main/java/com/capstone/dayj/plan/Plan.java
src/main/java/com/capstone/dayj/plan/PlanController.java
src/main/java/com/capstone/dayj/plan/PlanDto.java
src/main/java/com/capstone/dayj/plan/PlanRepository.java
src/main/java/com/capstone/dayj/plan/PlanService.java
src/main/java/com/capstone/dayj/post/Post.java
src/main/java/com/capstone/dayj/post/PostController.java
src/main/java/com/capstone/dayj/post/PostDto.java
src/main/java/com/capstone/dayj/post/PostRepository.java
src/main/java/com/capstone/dayj/post/PostService.java
src/main/java/com/capstone/dayj/setting/SettingController.java
src/main/java/com/capstone/dayj/setting/SettingService.java
src/main/java/com/capstone/dayj/tag/Tag.java
src/main/java/com/capstone/dayj/util/ImageUploader.java
src/main/resources/application-prod.yml
src/main/resources/application.yml

* 기존의 String이던 planTag와 postTag를 Tag Enum 클래스 타입으로 변경하였습니다.
* 태그는 총 7개로 (`HEALTH, STUDY, INVESTMENT, HOBBY, READING, CAREER, LIFESTYLE`)가 있습니다.
* 만약 대문자로 안 보내거나, enum 클래스에 없는 값이라면 500 서버 오류가 발생합니다.
* 없음
* 다 테스트해봐서 괜찮을 것 같아요
---

REFACTOR: change tag type to ENUM class

---

src/main/java/com/capstone/dayj/OauthSecurity/OAuth2SecurityConfiguration.java
src/main/java/com/capstone/dayj/post/PostController.java
src/main/java/com/capstone/dayj/post/PostService.java

* post의 like와 view 업데이트가 반영이 안된 상태로 엔티티를 반환하고 있는 문제 해결
* 없음
* 이미지 업로드 구현할 때, 여러 엔티티의 업데이트랑 Create 과정에서 생각보다 값이 덮어쓰여지거나 생략되는 상황이 많았습니다. 이런 코드가 있다면 한 번 검사해볼 필요가 있을 것 같아요. (제가 웬만한거는 다 바꿔놓긴 했는데 빠진 부분이 분명 있을 것 같습니다...)
---

REFACTOR: post (like, view) ordering

---

pom.xml
src/main/resources/application-prod.yml

add pom.xml build

---

src/main/java/com/capstone/dayj/statistics/StatisticsController.java

REFACTOR: statistics uri 수정

---

src/main/java/com/capstone/dayj/util/ImageUploader.java

REFACTOR: add logger on ImageUploader

---

src/main/java/com/capstone/dayj/friendGroup/FriendGroupDto.java
src/main/java/com/capstone/dayj/groupMember/GroupMemberDto.java

REFACTOR: FriendGroup Dto 수정

---

src/main/java/com/capstone/dayj/plan/PlanController.java
src/main/java/com/capstone/dayj/plan/PlanService.java

* PlanOption을 Plan 생성시에 같이 request로 받아서 한 번에 업데이트 하는 방식으로 변경하였습니다.
* 기존에는 Plan만 받고 PlanOption은 업데이트를 따로 하는 방식이었습니다.
* 없음
* X
---

REFACTOR: merge Plan Service and PlanOption Service
